# -*- coding: utf-8 -*-
"""calc-armadilhacdi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gxExe77BKXvGS00FbJriRXgCcS2lG6VU
"""

!pip install yfinance pandas_datareader
!pip install python-bcb

import requests
import json
import os
import pandas as pd
from bcb import sgs
from datetime import datetime, timedelta
from pathlib import Path
import urllib3

# Desabilita avisos de certificados inseguros
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# --- CONFIGURAÇÕES E CONSTANTES ---
CACHE_DIR = Path("cache")
CDI_CACHE_FILE = CACHE_DIR / "cdi.json"
USD_CACHE_FILE = CACHE_DIR / "usd.json"
START_DATE_HISTORY = "01/01/1996"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "Accept": "application/json"
}

# --- MÓDULO DE DADOS ---

def carregar_cache(caminho):
    if caminho.exists():
        try:
            with open(caminho, 'r') as f:
                return json.load(f)
        except:
            return {}
    return {}

def salvar_cache(caminho, dados):
    CACHE_DIR.mkdir(exist_ok=True)
    with open(caminho, 'w') as f:
        json.dump(dados, f)

def buscar_dados_cdi_olinda():
    """Tenta buscar CDI via interface OData (Olinda) que é mais estável no Colab."""
    print("Atualizando dados do CDI via API Olinda...")
    # Usando o endpoint de séries temporais do OData se disponível,
    # ou fallback para o SGS via proxy/mirror estável
    url = "https://api.bcb.gov.br/dados/serie/bcdata.sgs.12/dados?formato=json"

    try:
        # Adicionando cabeçalhos de simulação de browser completa para evitar 406
        response = requests.get(url, headers=HEADERS, timeout=25, verify=False)
        if response.status_code == 200:
            dados = response.json()
            return {datetime.strptime(i['data'], '%d/%m/%Y').strftime('%Y-%m-%d'): float(i['valor']) for i in dados}
    except:
        pass

    # Segunda tentativa: WebService SOAP com timeout estendido e hosts variados
    print("Tentando via WebService SOAP (Backup)...")
    soap_url = "https://www3.bcb.gov.br/wssgs/services/FachadaWSSGS"
    data_fim = datetime.now().strftime("%d/%m/%Y")
    soap_body = f"""<soapenv:Envelope xmlns:soapenv='http://schemas.xmlsoap.org/soap/envelope/' xmlns:res='http://publico.ws.casansgs.bcb.gov.br'>
       <soapenv:Body>
          <res:getValoresSeriesXML>
             <res:codigosSeries><res:long>12</res:long></res:codigosSeries>
             <res:dataInicio>{START_DATE_HISTORY}</res:dataInicio>
             <res:dataFim>{data_fim}</res:dataFim>
          </res:getValoresSeriesXML>
       </soapenv:Body>
    </soapenv:Envelope>"""

    try:
        res = requests.post(soap_url, data=soap_body, headers={"Content-Type": "text/xml"}, timeout=20, verify=False)
        if res.status_code == 200:
            content = res.text.replace('&lt;', '<').replace('&gt;', '>')
            cdi_dict = {}
            items = content.split('<ITEM>')
            for item in items[1:]:
                try:
                    d, m, a = item.split('dia="')[1].split('"')[0], item.split('mes="')[1].split('"')[0], item.split('ano="')[1].split('"')[0]
                    v = item.split('<VALOR>')[1].split('</VALOR>')[0].replace(',', '.')
                    cdi_dict[f"{a}-{m.zfill(2)}-{d.zfill(2)}"] = float(v)
                except: continue
            return cdi_dict
    except: pass

    return {}

def buscar_dados_usd(data_inicio_str, data_fim_str):
    print("Atualizando dados de Câmbio USD...")
    d1 = datetime.strptime(data_inicio_str, "%d/%m/%Y").strftime("%m-%d-%Y")
    d2 = datetime.today().strftime("%m-%d-%Y")
    url = f"https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/odata/CotacaoDolarPeriodo(dataInicial=@dataInicial,dataFinalCotacao=@dataFinalCotacao)?@dataInicial='{d1}'&@dataFinalCotacao='{d2}'&$format=json&$select=cotacaoVenda,dataHoraCotacao"
    try:
        res = requests.get(url, headers=HEADERS, timeout=20, verify=False)
        res.raise_for_status()
        dados = res.json().get('value', [])
        return {item['dataHoraCotacao'].split(' ')[0]: float(item['cotacaoVenda']) for item in dados}
    except:
        return {}

def sincronizar_dados():
    cdi_dict = carregar_cache(CDI_CACHE_FILE)
    usd_dict = carregar_cache(USD_CACHE_FILE)
    threshold = (datetime.now() - timedelta(days=2)).strftime("%Y-%m-%d")

    if not cdi_dict or max(cdi_dict.keys()) < threshold:
        novos_cdi = buscar_dados_cdi_olinda()
        if novos_cdi:
            cdi_dict.update(novos_cdi)
            salvar_cache(CDI_CACHE_FILE, cdi_dict)

    if not usd_dict or max(usd_dict.keys()) < threshold:
        novos_usd = buscar_dados_usd(START_DATE_HISTORY, datetime.now().strftime("%d/%m/%Y"))
        if novos_usd:
            usd_dict.update(novos_usd)
            salvar_cache(USD_CACHE_FILE, usd_dict)

    return cdi_dict, usd_dict

def get_valor_com_fallback(dicionario, data_alvo):
    data_dt = datetime.strptime(data_alvo, "%Y-%m-%d")
    for _ in range(15):
        str_dt = data_dt.strftime("%Y-%m-%d")
        if str_dt in dicionario: return dicionario[str_dt]
        data_dt -= timedelta(days=1)
    return None

def calcular_investimento(data_ini_br, data_fim_br, valor_brl, cdi_dict, usd_dict):
    d_ini = datetime.strptime(data_ini_br, "%d/%m/%Y").strftime("%Y-%m-%d")
    d_fim = datetime.strptime(data_fim_br, "%d/%m/%Y").strftime("%Y-%m-%d")
    fator_acumulado = 1.0
    encontrou_datas = False
    for dt in sorted(cdi_dict.keys()):
        if d_ini < dt <= d_fim:
            fator_acumulado *= (1 + (cdi_dict[dt] / 100))
            encontrou_datas = True
    if not encontrou_datas: raise ValueError("Dados de CDI insuficientes.")
    cot_ini = get_valor_com_fallback(usd_dict, d_ini)
    cot_fim = get_valor_com_fallback(usd_dict, d_fim)
    if not cot_ini or not cot_fim: raise ValueError("Cotação USD ausente.")
    v_final_brl = valor_brl * fator_acumulado
    return {
        "cdi": (fator_acumulado - 1) * 100, "v_brl": v_final_brl,
        "v_usd_ini": valor_brl / cot_ini, "v_usd_fim": v_final_brl / cot_fim,
        "c_ini": cot_ini, "c_fim": cot_fim
    }

def main():
    print("=== CALCULADORA CDI vs USD ===")
    try:
        cdi_data, usd_data = sincronizar_dados()
        if not cdi_data:
            print("Erro: API do Banco Central indisponível (406/DNS).")
            return
        d_ini = input("Início (DD/MM/YYYY): ")
        d_fim = input("Fim (DD/MM/YYYY): ")
        v_ini = float(input("Valor BRL: ").replace(',', '.'))
        res = calcular_investimento(d_ini, d_fim, v_ini, cdi_data, usd_data)
        print(f"\nCDI: {res['cdi']:.2f}% | R$ {v_ini:,.2f} -> R$ {res['v_brl']:,.2f}")
        print(f"USD: US$ {res['v_usd_ini']:,.2f} -> US$ {res['v_usd_fim']:,.2f}")
        print(f"Câmbio: R$ {res['c_ini']:.2f} -> R$ {res['c_fim']:.2f}")
    except Exception as e: print(f"Erro: {e}")

if __name__ == '__main__':
    main()

import json
from datetime import datetime, timedelta

def carregar_caches():
    with open('usd_cache.json', 'r') as f:
        usd = json.load(f)
    with open('cdi_cache.json', 'r') as f:
        cdi = json.load(f)
    return usd, cdi

def obter_valor_com_fallback(dicionario, data_alvo):
    data_dt = datetime.strptime(data_alvo, "%Y-%m-%d")
    for _ in range(15):
        str_dt = data_dt.strftime("%Y-%m-%d")
        if str_dt in dicionario:
            return dicionario[str_dt], str_dt
        data_dt -= timedelta(days=1)
    return None, None

def calcular_resultado(data_ini_br, data_fim_br, valor_inicial_brl):
    usd_dict, cdi_dict = carregar_caches()
    d_ini = datetime.strptime(data_ini_br, "%d/%m/%Y").strftime("%Y-%m-%d")
    d_fim = datetime.strptime(data_fim_br, "%d/%m/%Y").strftime("%Y-%m-%d")

    # 1. CDI Acumulado (Regra exata validada)
    fator_acumulado = 1.0
    datas_ordenadas = sorted(cdi_dict.keys())
    for data in datas_ordenadas:
        if d_ini <= data < d_fim:
            taxa_diaria_perc = cdi_dict[data]
            fator_acumulado *= (1 + (taxa_diaria_perc / 100))

    # 2. Cotações USD
    cot_ini, _ = obter_valor_com_fallback(usd_dict, d_ini)
    cot_fim, _ = obter_valor_com_fallback(usd_dict, d_fim)

    if cot_ini is None or cot_fim is None:
        return "Erro: Dados de cotação insuficientes."

    # 3. Cálculos Financeiros
    v_final_brl = valor_inicial_brl * fator_acumulado
    v_ini_usd = valor_inicial_brl / cot_ini
    v_final_usd_ajustado = v_final_brl / cot_fim

    # Ganho real em USD (Comparação do investimento corrigido vs capital em dólar)
    rentabilidade_usd_real = (v_final_usd_ajustado / v_ini_usd - 1) * 100

    return {
        "periodo": f"{data_ini_br} a {data_fim_br}",
        "indice_correcao": fator_acumulado,
        "cdi_perc": (fator_acumulado - 1) * 100,
        "brl_ini": valor_inicial_brl,
        "brl_fim": v_final_brl,
        "usd_ini": v_ini_usd,
        "usd_fim_com_cdi": v_final_usd_ajustado,
        "cotacao_ini": cot_ini,
        "cotacao_fim": cot_fim,
        "rentabilidade_usd_real": rentabilidade_usd_real
    }

import requests
import json
from datetime import datetime
from pathlib import Path

def buscar_historico_ptax(data_inicio="01-01-1996"):
    """
    Busca o histórico de cotações BRL/USD (venda) via API Olinda PTAX.
    Retorna um dicionário: { 'YYYY-MM-DD': cotação }
    """
    print(f"Iniciando coleta de dados USD desde {data_inicio}...")

    # Data final para a consulta (hoje)
    hoje = datetime.now().strftime("%m-%d-%Y")

    # URL da API Olinda (PTAX)
    url = (
        "https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/odata/"
        "CotacaoDolarPeriodo(dataInicial=@dataInicial,dataFinalCotacao=@dataFinalCotacao)?"
        f"@dataInicial='{data_inicio}'&@dataFinalCotacao='{hoje}'"
        "&$format=json&$select=cotacaoVenda,dataHoraCotacao"
    )

    try:
        # Realiza a requisição
        response = requests.get(url, timeout=45)
        response.raise_for_status()

        dados_brutos = response.json().get('value', [])

        # Processa os dados para o formato de dicionário
        usd_dict = {}
        for item in dados_brutos:
            # A data vem como '2023-10-27 13:05:45.123', pegamos apenas a parte da data
            data_iso = item['dataHoraCotacao'].split(' ')[0]
            usd_dict[data_iso] = float(item['cotacaoVenda'])

        print(f"Sucesso! {len(usd_dict)} cotações carregadas.")
        return usd_dict

    except Exception as e:
        print(f"Erro na coleta de dados: {e}")
        return {}

def salvar_cache(dados, nome_arquivo="usd_cache.json"):
    with open(nome_arquivo, 'w') as f:
        json.dump(dados, f)
    print(f"Cache salvo em: {nome_arquivo}")

# --- EXECUÇÃO ---

# 1. Busca os dados
usd_history = buscar_historico_ptax()

# 2. Salva em cache se houver dados
if usd_history:
    salvar_cache(usd_history)

# 3. Exibe as 5 cotações mais recentes para conferência
print("\nÚltimas 5 cotações encontradas:")
datas_ordenadas = sorted(usd_history.keys())
for data in datas_ordenadas[-5:]:
    print(f"{data}: R$ {usd_history[data]:.4f}")

## GRÁFICO DA VARIAÇÃO PERCENTUAL EM DADO PERÍODO DE TEMPO, SEM LIMITAÇÃO, DESDE 1996 ##

import matplotlib.pyplot as plt
from bcb import sgs
import pandas as pd
from datetime import datetime, timedelta
import json
import os

CACHE_FILE = "finance_cache.json"

def atualizar_e_carregar_dados():
    """Busca dados em blocos de 10 anos para contornar o limite da API e salva em cache."""
    hoje = datetime.now()
    df_cache = pd.DataFrame()

    if os.path.exists(CACHE_FILE):
        try:
            with open(CACHE_FILE, 'r') as f:
                cache = json.load(f)
                if cache:
                    df_cache = pd.DataFrame.from_dict(cache, orient='index')
                    df_cache.index = pd.to_datetime(df_cache.index)
        except Exception as e:
            print(f"Aviso: Cache corrompido, reiniciando... ({e})")
            os.remove(CACHE_FILE)

    if df_cache.empty:
        data_inicio_busca = datetime(1996, 1, 1)
    else:
        data_inicio_busca = df_cache.index.max() + timedelta(days=1)

    if data_inicio_busca < hoje - timedelta(days=1):
        print(f"Sincronizando dados desde {data_inicio_busca.strftime('%d/%m/%Y')}...")
        novos_dfs = []
        ponto_partida = data_inicio_busca

        while ponto_partida < hoje:
            ponto_final = min(ponto_partida + timedelta(days=365*9), hoje)
            try:
                chunk = sgs.get({'cdi': 12, 'usd': 1, 'ipca': 433},
                                start=ponto_partida, end=ponto_final)
                if not chunk.empty:
                    novos_dfs.append(chunk)
            except Exception as e:
                print(f"Aviso no bloco {ponto_partida.year}: {e}")
            ponto_partida = ponto_final + timedelta(days=1)

        if novos_dfs:
            df_novo = pd.concat(novos_dfs)
            df_completo = pd.concat([df_cache, df_novo]).sort_index()
            df_completo = df_completo[~df_completo.index.duplicated(keep='last')]

            df_para_cache = df_completo.copy()
            df_para_cache.index = df_para_cache.index.strftime('%Y-%m-%d')
            df_para_cache = df_para_cache.fillna(0)

            with open(CACHE_FILE, 'w') as f:
                json.dump(df_para_cache.to_dict(orient='index'), f)
            return df_completo

    return df_cache

def gerar_grafico_completo():
    try:
        df = atualizar_e_carregar_dados()
        if df.empty:
            print("Erro: Falha ao obter dados.")
            return

        d1_str = input("Início (DD/MM/YYYY): ")
        d2_str = input("Fim (DD/MM/YYYY): ")
        d1, d2 = pd.to_datetime(d1_str, dayfirst=True), pd.to_datetime(d2_str, dayfirst=True)

        df_view = df.loc[d1:d2].copy()
        if df_view.empty:
            print("Sem dados para o período selecionado.")
            return

        # Correção Crítica: Garantir que o USD não comece com zero ou NaN
        df_view['usd'] = df_view['usd'].replace(0, pd.NA).ffill().bfill()
        df_view['ipca'] = df_view['ipca'].fillna(0)
        df_view['cdi'] = df_view['cdi'].fillna(0)

        # Cálculos de evolução (Base 0% no primeiro dia válido)
        df_view['evolucao_cdi'] = (1 + df_view['cdi'] / 100).cumprod() - 1
        df_view['evolucao_ipca'] = (1 + df_view['ipca'] / 100).cumprod() - 1

        usd_inicial = df_view['usd'].iloc[0]
        df_view['evolucao_usd'] = (df_view['usd'] / usd_inicial) - 1

        # Ganho Real em USD: ((1 + CDI_acum) / (1 + USD_var)) - 1
        df_view['ganho_real_usd'] = ((1 + df_view['evolucao_cdi']) / (1 + df_view['evolucao_usd'])) - 1

        # Resample mensal para o gráfico
        plot_df = df_view[['evolucao_cdi', 'evolucao_ipca', 'evolucao_usd', 'ganho_real_usd']] * 100
        plot_df_mensal = plot_df.resample('ME').last()

        plt.figure(figsize=(12, 7))
        plt.plot(plot_df_mensal.index, plot_df_mensal['evolucao_cdi'], label='CDI (%)', color='blue', linewidth=2)
        plt.plot(plot_df_mensal.index, plot_df_mensal['evolucao_ipca'], label='IPCA (%)', color='orange', linestyle=':', linewidth=2)
        plt.plot(plot_df_mensal.index, plot_df_mensal['evolucao_usd'], label='USD (%)', color='green', alpha=0.6)
        plt.plot(plot_df_mensal.index, plot_df_mensal['ganho_real_usd'], label='Ganho Real USD (%)', color='red', linewidth=2)

        plt.title(f'Comparativo Histórico: {d1_str} a {d2_str}')
        plt.ylabel('Variação Acumulada (%)')
        plt.xlabel('Data')
        plt.legend(loc='upper left')
        plt.grid(True, alpha=0.3)
        plt.axhline(0, color='black', linewidth=1)
        plt.show()

    except Exception as e: print(f"Erro: {e}")

gerar_grafico_completo()

## CALCULADORA ANALÍTICA, COM LIMITAÇÃO DE 10 ANOS ##

def executar_calculo():
    try:
        d1, d2 = input("Início (DD/MM/YYYY): "), input("Fim (DD/MM/YYYY): ")
        v_ini = float(input("Valor BRL: ").replace(',', '.'))

        # Busca CDI (12) e Dólar PTAX (1) de uma vez
        df = sgs.get({'cdi': 12, 'usd': 1},
                     start=datetime.strptime(d1, '%d/%m/%Y'),
                     end=datetime.strptime(d2, '%d/%m/%Y'))

        fator = (1 + df['cdi'][:-1] / 100).prod()
        v_fim = v_ini * fator

        c_ini, c_fim = df['usd'].iloc[0], df['usd'].iloc[-1]
        u_ini, u_fim = v_ini / c_ini, v_fim / c_fim

        print(f"\n--- RESULTADO ---\nFator CDI: {fator:.8f} (+{(fator-1)*100:.2f}%)")
        print(f"BRL: R$ {v_ini:,.2f} -> R$ {v_fim:,.2f}")
        print(f"USD: US$ {u_ini:,.2f} -> US$ {u_fim:,.2f} (Câmbio: {c_ini:.2f} -> {c_fim:.2f})")
        print(f"Ganho Real em USD: {(u_fim/u_ini - 1)*100:+.2f}%")
    except Exception as e: print(f"Erro: {e}")

executar_calculo()