# -*- coding: utf-8 -*-
"""calculo-inflacaoamericana.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F3A2NMhteq5NlnhrlwfCCxeyP8gi4Uka
"""

import pandas as pd
from fredapi import Fred
from datetime import datetime

# --- 1. Obtenha sua chave de API do FRED ---
# Você pode obter uma chave de API gratuita em: https://fred.stlouisfed.org/docs/api/api_key.html
# Substitua 'YOUR_FRED_API_KEY' pela sua chave de API real ou use input().
# Exemplo: fred_api_key = input("Por favor, insira sua chave de API do FRED: ")
fred_api_key = "a56c4ffe739cef6a0f8b4ad483e8ecec" # Substitua pela sua chave REAL

# Inicializa a API do FRED
fred = Fred(api_key=fred_api_key)

# --- 2. Baixar dados do CPI (Consumer Price Index) ---
# A série 'CPIAUCSL' representa o Índice de Preços ao Consumidor para Todos os Consumidores Urbanos:
# Todos os Itens nos EUA, Média das Cidades, Ajustado Sazonalmente.
# É um dos índices mais comuns para medir a inflação americana.
print("Baixando dados do CPI (CPIAUCSL) desde 1996...")
try:
    cpi_series = fred.get_series('CPIAUCSL', start_date='1996-01-01')
    if cpi_series.empty:
        raise ValueError("Nenhum dado do CPI foi retornado. Verifique a chave da API e o ID da série.")
    print("Dados do CPI baixados com sucesso!")

    # Converter a Série em DataFrame
    cpi_data_df = cpi_series.to_frame(name='CPI_Value')
    print("\n--- DataFrame do CPI --- ")
    display(cpi_data_df.head())

except Exception as e:
    print(f"Erro ao baixar dados do CPI: {e}")
    print("Por favor, verifique se a chave de API do FRED está correta e funcionando.")
    cpi_data_df = pd.DataFrame() # Cria um DataFrame vazio para evitar erros posteriores

# --- 3. Criar o dicionário histórico de inflação ---
# Convertendo a série de CPI do DataFrame para um dicionário, com datas como chaves (datetime) e valores do CPI
if not cpi_data_df.empty:
    dicionario_inflacao_eua = cpi_data_df['CPI_Value'].to_dict()
    print(f"\nDicionário de inflação criado com {len(dicionario_inflacao_eua)} entradas.")

    # Premissa: Informar o período do dicionário
    data_mais_antiga = min(dicionario_inflacao_eua.keys()).strftime('%Y-%m-%d')
    data_mais_recente = max(dicionario_inflacao_eua.keys()).strftime('%Y-%m-%d')
    print(f"Premissa: O dicionário de inflação contém dados de {data_mais_antiga} a {data_mais_recente}.")
    print("Para atualizar com os dados mais recentes do FRED, basta executar esta célula novamente.")

else:
    dicionario_inflacao_eua = {}
    print("Dicionário de inflação vazio devido a falha no download dos dados.")

# --- 4. Função para calcular a inflação acumulada ---
def calcular_inflacao_acumulada(data_inicio: str, data_fim: str, inflacao_dict: dict) -> float:
    """
    Calcula a inflação acumulada entre duas datas usando um dicionário de dados de inflação.
    Inclui projeção para datas de fim futuras até o mês atual, usando a média dos últimos 12 meses.

    Args:
        data_inicio (str): Data de início no formato 'AAAA-MM-DD'.
        data_fim (str): Data de fim no formato 'AAAA-MM-DD'.
        inflacao_dict (dict): Dicionário com datas (datetime) como chaves e valores de CPI.

    Returns:
        float: A inflação acumulada como um percentual (ex: 0.20 para 20%).
               Retorna None se os dados para as datas não forem encontrados, se a data de início for posterior à data de fim,
               ou se a data de fim for muito no futuro.
    """
    try:
        dt_inicio = pd.to_datetime(data_inicio)
        dt_fim = pd.to_datetime(data_fim)
    except ValueError:
        print("Erro: Formato de data inválido. Use 'AAAA-MM-DD'.")
        return None

    if dt_inicio > dt_fim:
        print("Erro: A data de início não pode ser posterior à data de fim.")
        return None

    sorted_dates = sorted(inflacao_dict.keys())
    if not sorted_dates:
        print("Erro: Dicionário de inflação vazio.")
        return None

    max_available_date = sorted_dates[-1]
    # Normalize today to the beginning of the current month
    today = datetime.now().replace(day=1, hour=0, minute=0, second=0, microsecond=0)

    cpi_fim_value = None
    projection_made = False

    # Case 1: dt_fim is in the future beyond today's month
    if dt_fim > today:
        print(f"Erro: Não é possível calcular a inflação para datas futuras além do mês atual ({today.strftime('%Y-%m-%d')}).")
        return None

    # Case 2: dt_fim is after the last available data but within or before today (projection needed)
    if dt_fim > max_available_date:
        print(f"Aviso: Dados de inflação para {data_fim} não estão disponíveis. Será feita uma projeção baseada nos últimos 12 meses.")
        projection_made = True

        # Ensure we have enough data for a 12-month rolling average (at least 13 months for 12 changes)
        if len(sorted_dates) < 13:
            print("Erro: Não há dados suficientes (pelo menos 13 meses) no dicionário para calcular a projeção baseada nos últimos 12 meses.")
            return None

        # Get the last 13 CPI values (for 12 monthly changes)
        # Use pandas Series to easily calculate percentage change and handle NaNs if any (though FRED data should be clean)
        recent_cpi_series_for_calc = pd.Series([inflacao_dict[date] for date in sorted_dates[-13:]], index=sorted_dates[-13:])

        # Calculate monthly percentage changes for the last 12 months
        monthly_changes = recent_cpi_series_for_calc.pct_change().dropna()

        # Calculate the average monthly percentage change
        if monthly_changes.empty:
            print("Erro: Não foi possível calcular as variações mensais para a projeção.")
            return None

        avg_monthly_change = monthly_changes.mean()

        # Project CPI value for dt_fim
        projected_cpi_current = inflacao_dict[max_available_date]
        current_projection_date = max_available_date

        while current_projection_date < dt_fim:
            # Move to the next month
            if current_projection_date.month == 12:
                current_projection_date = current_projection_date.replace(year=current_projection_date.year + 1, month=1)
            else:
                current_projection_date = current_projection_date.replace(month=current_projection_date.month + 1)

            # Apply average monthly change
            projected_cpi_current *= (1 + avg_monthly_change)
        cpi_fim_value = projected_cpi_current

    else: # Case 3: dt_fim is within the available historical data
        # Find the closest CPI value for dt_fim
        found_cpi_fim = False
        for date_key in sorted_dates:
            if date_key >= dt_fim:
                cpi_fim_value = inflacao_dict[date_key]
                found_cpi_fim = True
                break
        # If dt_fim is earlier than the earliest available data
        if not found_cpi_fim and dt_fim < sorted_dates[0]:
            cpi_fim_value = inflacao_dict[sorted_dates[0]]

    # Find the CPI value for dt_inicio
    cpi_inicio_value = None
    found_cpi_inicio = False
    for date_key in sorted_dates:
        if date_key >= dt_inicio:
            cpi_inicio_value = inflacao_dict[date_key]
            break
    # If dt_inicio is earlier than the earliest available data
    if cpi_inicio_value is None and dt_inicio < sorted_dates[0]:
        cpi_inicio_value = inflacao_dict[sorted_dates[0]]


    if cpi_inicio_value is None:
        print(f"Erro: Dados do CPI não encontrados para a data de início: {data_inicio}")
        return None
    if cpi_fim_value is None:
        # This case should ideally be prevented by earlier checks (dt_fim > today or projection logic)
        print(f"Erro: Dados do CPI não encontrados para a data de fim: {data_fim}")
        return None

    if cpi_inicio_value == 0:
        print("Erro: Valor do CPI inicial é zero, não é possível calcular a inflação.")
        return None

    inflacao_acumulada = (cpi_fim_value / cpi_inicio_value) - 1
    if projection_made:
        # The prompt mentioned "The returned value includes a clear message indicating it's a projection."
        # This message is printed above, but the return type is float, so the message is a side effect.
        return inflacao_acumulada
    else:
        return inflacao_acumulada

# --- Exemplo de uso ---
if dicionario_inflacao_eua:
    print("\n--- Exemplo de uso da função ---")

    # Exemplo 1: Data de fim futura (além do mês atual) - deve retornar erro
    data_inicio_exemplo_1 = '2020-01-01'
    data_fim_exemplo_1 = '2026-04-01' # Assuming today is before 2026-04-01
    print(f"\nTentando calcular inflação de {data_inicio_exemplo_1} a {data_fim_exemplo_1}:")
    inflacao_periodo_1 = calcular_inflacao_acumulada(
        data_inicio_exemplo_1, data_fim_exemplo_1, dicionario_inflacao_eua
    )
    if inflacao_periodo_1 is not None:
        print(f"Inflação acumulada: {inflacao_periodo_1:.2%}")


    # Exemplo 2: Data de fim que requer projeção (até o mês atual)
    # Define data_fim como o primeiro dia do mês atual para simular projeção
    data_fim_projecao = datetime.now().replace(day=1).strftime('%Y-%m-%d')
    data_inicio_exemplo_2 = '2020-01-01'
    print(f"\nTentando calcular inflação de {data_inicio_exemplo_2} a {data_fim_projecao} (com projeção, se necessário):")
    inflacao_periodo_2 = calcular_inflacao_acumulada(
        data_inicio_exemplo_2, data_fim_projecao, dicionario_inflacao_eua
    )
    if inflacao_periodo_2 is not None:
        print(f"Inflação acumulada: {inflacao_periodo_2:.2%}")

    # Exemplo 3: Período totalmente dentro dos dados históricos
    data_inicio_exemplo_3 = '2010-06-01'
    data_fim_exemplo_3 = '2015-06-01'
    print(f"\nTentando calcular inflação de {data_inicio_exemplo_3} a {data_fim_exemplo_3} (dados históricos):")
    inflacao_periodo_3 = calcular_inflacao_acumulada(
        data_inicio_exemplo_3, data_fim_exemplo_3, dicionario_inflacao_eua
    )
    if inflacao_periodo_3 is not None:
        print(f"Inflação acumulada: {inflacao_periodo_3:.2%}")

    # Exemplo 4: Data de início posterior à data de fim
    data_inicio_exemplo_4 = '2015-01-01'
    data_fim_exemplo_4 = '2010-01-01'
    print(f"\nTentando calcular inflação de {data_inicio_exemplo_4} a {data_fim_exemplo_4} (data de início > data de fim):")
    inflacao_periodo_4 = calcular_inflacao_acumulada(
        data_inicio_exemplo_4, data_fim_exemplo_4, dicionario_inflacao_eua
    )
    if inflacao_periodo_4 is not None:
        print(f"Inflação acumulada: {inflacao_periodo_4:.2%}")